// <auto-generated />
namespace Movie_Mania_2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Movie_model_modification_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movie_model_modification_1));
        
        string IMigrationMetadata.Id
        {
            get { return "202111301826157_Movie_model_modification_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
